# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jens Ivar JÃ¸rdre
title: Senior Consultant
emails:
  - jens.ivar.jordre@webstep.no
  - jijordre@gmail.com
website: jijordre.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: jijordre
github_username: jijordre
linkedin_username: jijordre
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jijordre
# flickr_username: jekyll
# instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jijordre
# youtube_username: jijordre
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile3.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi,

  I am a technically focused developer and architect with a PhD in nuclear physics, possessing a rare combination of deep technical understanding and strategic leadership experience from C-level roles. I practice value-based leadership that fosters trust and collaboration, creating ownership and motivation within my teams through the clear communication of goals.

  My expertise spans from low-level system programming to modern Web3 architecture and cloud-based microservices, enabling me to deliver solutions that unite scientific precision with commercial value. I thrive in bridging the gap between business and technology, humanizing technology, designing sustainable, high-performance systems that solve actual business needs even within strict regulatory frameworks. As a quality-conscious and results-oriented professional, I bring infectious enthusiasm to multidisciplinary teams in both distributed and co-located environments.

content:
  - title: Selected Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: DNB Carnegie
        link: www.dnb.no/en/markets
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          At DNB Carnegie, I work as a System Developer on two major initiatives: Project FIND and the Murex implementation.

          For the FIND project, I help establish a central Master Data Management system for financial instruments, designing a scalable data model to import data from sources like Bloomberg and Nordic Bond Pricing. I also implement integrations to export this data to Murex and build a frontend for the business side to manage financial instruments.

          Regarding the Murex project, I focus on integrating the trading platform with DNB Carnegie's existing portfolio, a.o. by implementing a backend solution for reporting money market data to the Central Banks of Norway and Sweden using ISO 20022 standards. My work ensures simplified trading flows and optimized cost structures for data collection.

          <b>TechStack: </b><em>Java, Kotlin, Spring Boot, JPA, Hibernate, Kafka, IBM MQ, PostgreSQL, Oracle Database, IBM DB2, Docker, Kubernetes, OpenShift, Argo CD, Azure DevOps</em>

      - layout: top-middle
        title: CBDC Retail Sandbox for the Central Bank of Norway
        link: www.norges-bank.no/en/topics/financial-stability/cbdc
        additional_links:
          - title: nahmii
            icon: fab fa-github
            url: github.com/norges-bank
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          As a System Developer and architect for the CBDC Retail Sandbox project of the Central Bank of Norway, I was responsible for the management, design, and implementation of a technical sandbox to evaluate Central Bank Digital Currency (CBDC).

          We designed a comprehensive architecture that included a private Ethereum-based blockchain backend, specialized smart contracts, and a frontend interface. My role involved developing these smart contracts to support various retail payment scenarios and integrating the frontend with third-party authentication solutions. Additionally, we provided strategic advice to the Central Bank of Norway on critical technical decisions, such as the choice of token standards and bridge technologies. 

          This contribution has enabled the Central Bank of Norway to test a broad spectrum of scenarios and build solid first-hand expertise with key components of the blockchain ecosystem.

          <b>TechStack: </b><em>Blockchain, Web3, Ethereum, Solidity, JavaScript, TypeScript, Node.js, Azure, AWS, Web3Auth, Docker, Kubernetes, Hardhat, Truffle, Ethers</em>

      - layout: top-middle
        title: Nahmii
        link: www.nahmii.io
        additional_links:
          - title: nahmii
            icon: fab fa-github
            url: github.com/nahmii
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          During my tenure as CSO and CTO at Nahmii, I led the architecture and development of our 2nd layer scaling solutions for Ethereum, spanning versions 1.0, 2.0, and 3.0.

          The Nahmii solution focuses on addressing critical scaling issues by minimizing transaction costs and latency while ensuring immediate finality and increasing bandwidth. For Nahmii 1.0, we designed a hybrid solution that combined decentralized applications with a client-server model to handle high transaction rates. Later, I directed the implementation of Nahmii 2.0 as an Ethereum-compatible platform and Nahmii 3.0 as an Ethereum-equivalent solution, allowing standard Ethereum contracts to be utilized with little to no modification.

          My role involved technical leadership for teams ranging from 5 to 20 developers and operations engineers, where I oversaw the development of smart contracts, microservices, SDKs, and frontends. Additionally, I enjoyed business development towards new and existing customers and setting up service environments for standard lifecycle stages.

          <b>TechStack: </b><em>Blockchain, Web3, Ethereum, Solidity, Go, JavaScript, TypeScript, Node.js, AWS, Docker, Kubernetes, Hardhat, Truffle, Ethers</em>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Webstep AS
        link: www.webstep.no
        epochs:
          - sub_title: Senior Consultant
            caption: August 2024 - Present
          - sub_title: Senior Consultant
            caption: April 2020 - April 2022
          - sub_title: Senior Consultant
            caption: May 2007 - November 2017
        quote: >
          Webstep is a non-bureaucratic company tailored for clever people.
        description: | # this will include new lines to allow paragraphs
          As a Senior Consultant at Webstep, I currently leverage my expertise to modernize financial infrastructure for DNB Carnegie, focusing on cost optimization and operational stability through the FIND and Murex projects. My work designing scalable data models and automating trading flows has reinforced the importance of robust architecture in high-stakes financial environments.

          Previously, I delivered social value through Webstep's Project Samla, where I architected a serverless AWS solution that empowers municipalities with data to improve public health decision-making. My extensive tenure with Statoil allowed me to transition between roles as a System Developer, Architect, and Business Process Modeler, teaching me how to effectively bridge the gap between complex technical implementations and strategic business needs. There, I enhanced operational workflows and compliance by harmonizing governing documentation and developed a well-completion system. Engagements with clients like Avinor and Delfi Data further broadened my industry scope, ranging from aviation data integration to banking advisory tools.

          Throughout these projects, I have learned to navigate strict regulatory frameworks while delivering high-performance solutions, whether visualizing seismic data for the oil industry or managing sensitive financial instruments. This diverse experience has honed my ability to unite scientific precision with commercial value, ensuring technical decisions directly support the customer's core objectives.

      - layout: left
        title: Nahmii AS
        link: www.nahmii.io
        epochs:
          - sub_title: Chief Technology Officer
            caption: November 2019 - August 2024
          - sub_title: Chief Science Officer
            caption: November 2017 - November 2019
        quote: >
          The Nahmii architecture offers unprecedented scalability of Ethereum equivalent blockchains.
        description: | # this will include new lines to allow paragraphs
          During my tenure as CSO and CTO at Nahmii, I led the strategic architecture and development of our 2nd layer Ethereum scaling solutions, evolving the platform through three major versions to address critical bottlenecks like transaction costs and latency. This work provided significant value by delivering immediate finality and high bandwidth, managed through technical leadership of development teams and operations engineers. 

          I also took on a hands-on role as System Developer and Architect for the Norwegian Central Bank, where I managed the design and implementation of a technical sandbox to evaluate Central Bank Digital Currency (CBDC). This contribution was vital in enabling the Norwegian Central Bank to test retail payment scenarios practically, thereby building solid, first-hand expertise within the blockchain ecosystem. My time at Nahmii thus spanned from high-level executive strategy and business development to deep technical implementation, bridging the gap between commercial scaling needs and national financial experimentation.

      - layout: left
        title: NordicNeuroLab AS
        link: www.nordicneurolab.com
        sub_title: Developer
        caption: February 2005 - April 2007
        quote: >
          We are dedicated to bringing the most advanced neuro-imaging tools to market while making functional MRI programs easy to implement.
        description: | # this will include new lines to allow paragraphs
          NordicNeuroLab provides products and solutions that support the field of functional MR imaging of the human brain. I took part in the development of their BOLD, Diffusion/DTI, and Perfusion/DCE analysis imaging software called 'nordicICE'. I focused on multi-planar visualization features and affine transformations as well as segmentation of structural pixel data for brain tissue extraction.

      - layout: left
        title: Department of Physics, University of Oslo
        link: www.uio.no/en/ift
        sub_title: PhD Candidate
        caption: July 2000 - June 2003
        quote: >
          The research conducted here ranges from elementary particle physics to material science and energy research, from space science to medical physics.
        description: | # this will include new lines to allow paragraphs
          My work included the development of analytical algorithms for experimental nuclear collision data w.r.t. particle identification and characterization, simulation and modeling of physical systems, as well as the design and development of software for calibration and monitoring of detectors and experiments. One year was spent at Brookhaven National Laboratory, NY, USA.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Bergen, Bergen, Norway
        link: www.uib.no/en/ift
        caption: 2000 - 2005
        sub_title: Doctor of Philosophy (Ph.D.) in High Energy Nuclear Physics
        quote: >
          The University of Bergen (UiB) is an internationally recognised research university. Academic diversity and high quality are fundamental for us. UiB is the most cited university in Norway.
        description: | # this will include new lines to allow paragraphs
          The thesis ["Rapidity and transverse momentum spectra and the reaction dynamics in Au + Au collisions at RHIC"](/data/phd-thesis.pdf){:target="_blank"}  describes various dynamic models for collisions of heavy atomic nuclei at high energies. These models are discussed in light of my own experimental results from the BRAHMS experiment at Brookhaven National Laboratory, NY, USA.

      - layout: left
        title: University of Bergen, Bergen, Norway
        link: www.uib.no/en/ift
        caption: 1994 - 2000
        sub_title: Master of Science in High Energy Nuclear Physics
        quote: >
          The University of Bergen (UiB) is an internationally recognised research university. Academic diversity and high quality are fundamental for us. UiB is the most cited university in Norway.
        description: | # this will include new lines to allow paragraphs
          The work described in the thesis "Performance of the time projection chambers of the BRAHMS experiment at RHIC" involved hardware and functional testing of time projection chambers. Detectors of this type lay the groundwork for particle detection capabilities in the BRAHMS experiment at Brookhaven National Laboratory, NY, USA.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my extra-curricular activities include
      - Hanging out with family and friends
      - Reading books
      - Playing music on electric or acoustic bass
      - Hiking and going to the gym

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
